### ISSUE TITLE
Make a 0.4.0 PyPI/npm release 

### ISSUE THREAD

**Issue by bollwyvl** [MarketSquare/jupyterlab_robotmode#13]
There's a fair amount of unreleased content on `main`. It would be good to get this out there so it can be used with JupyterLab 3.x.

**Comment by martinRenou** [comment]
@bollwyvl I sent you an invite to be a maintainer of the PyPI package (I realize I was the only maintainer, not good)

**Comment by bollwyvl** [comment]
Thanks, accepted: will move forward with an 0.4.0 release soonish, and then we can start #14...

**Comment by bollwyvl** [comment]
The pypi release is up:
- https://pypi.org/project/jupyterlab-robotmode/0.4.0/
And a WIP conda-forge PR:
- https://github.com/conda-forge/jupyterlab_robotmode-feedstock/pull/3

I see we haven't been publishing to npm for a while... not a big deal for this release, but perhaps looking forward we will want to resume the practice.
